% This test file was generated by Copilot. Validate the generated output before use.
classdef CodeGenMexTest < matlab.unittest.TestCase
    properties
        codeGen
    end

    methods(TestMethodSetup)
        function createCodeGen(testCase)
            testCase.codeGen = CodeGenMex();
        end
    end

    methods(Test)
        function testConfig(testCase)
            testCase.codeGen.config();
            testCase.verifyEqual(testCase.codeGen.cfg.Name, 'strata_trapper-mex');
            testCase.verifyEqual(testCase.codeGen.cfg.Description, ...
                'MEX-compiled StrataTrapper functions');
            testCase.verifyEqual(testCase.codeGen.cfg.TargetLang, 'C++');
            testCase.verifyEqual(testCase.codeGen.cfg.NumberOfCpuThreads, int32(32));
        end

        function testBuild(testCase)
            testCase.codeGen.config();
            a = int32(2);
            b = int32(2);
            sum = add_mex_test(a,b);
            testCase.codeGen.build_with({"-o","add_mex_test","-v"},'add_mex_test');
            % Check if the MEX file was created
            testCase.verifyTrue(exist('add_mex_test', 'file') == 3);
            sum_mex = add_mex_test(a,b);
            testCase.verifyTrue(sum_mex == sum); % test compiled MEX function
        end

        function testClear(testCase)
            testCase.codeGen.config();
            testCase.codeGen.build_with({"-o","add_mex_test"},'add_mex_test');
            testCase.codeGen.clear();
            % Check if the MEX file was deleted
            testCase.verifyTrue(exist('add_mex_test', 'file') == 2);
        end
    end
end
