function [] = ogs_export(strata_trapped, args)
arguments
    strata_trapped (1,1) struct
    args.output_folder  char   = 'ogs'
    args.default_poro (:,1) double = []
    args.default_perm (:,3) double = []
    args.satnum = [];
end

mkdir(args.output_folder);

output_prefix = append(args.output_folder,'/');

grid = strata_trapped.grid;

% export porosity
write_poro(output_prefix,grid,strata_trapped.porosity,strata_trapped.idx,args.default_poro);

% export fine-scale curves
strata_trapped.params.export_ogs(strata_trapped.saturation,[output_prefix,'chc.inc']);

% export upscaled curves
generate_sfn(strata_trapped,output_prefix,'.data',1);

% export curve mappings
write_krnum(output_prefix,strata_trapped.grid,strata_trapped.idx,...
    numel(strata_trapped.params),args.satnum);

% export permeability
write_perm(output_prefix,strata_trapped.grid,strata_trapped.permeability,strata_trapped.idx,...
    args.default_perm);

% create grid properties include file
grid_fid = fopen([output_prefix,'grid.inc'],'wb','native','UTF-8');

fprintf(grid_fid,...
    "INCLUDE\n" + ...
    """PORO.inc"" /\n" + ...
    "\n" + ...
    "INCLUDE\n" + ...
    """PERMX.inc"" /\n" + ...
    "\n" + ...
    "INCLUDE\n" + ...
    """PERMY.inc"" /\n" + ...
    "\n" + ...
    "INCLUDE\n" + ...
    """PERMZ.inc"" /\n" + ...
    "\n" + ...
    "INCLUDE\n" + ...
    """KRNUMX.inc"" /\n" + ...
    "\n" + ...
    "INCLUDE\n" + ...
    """KRNUMY.inc"" /\n" + ...
    "\n" + ...
    "INCLUDE\n" + ...
    """KRNUMZ.inc"" /\n" + ...
    "\n");

fclose(grid_fid);

% create curves include file
curve_fid = fopen([output_prefix,'curves.inc'],'wb','native','UTF-8');

fprintf(curve_fid,...
    "EXTERNAL_FILE ""chc.inc""\n" + ...
    "EXTERNAL_FILE ""chcx.data""\n" + ...
    "EXTERNAL_FILE ""chcy.data""\n" + ...
    "EXTERNAL_FILE ""chcz.data""\n" + ...
    "\n");

fclose(curve_fid);

end
