function generate_sfn(strata_trapped,prefix,inc_ext,offset)
arguments
    strata_trapped
    prefix char
    inc_ext char
    offset (1,1) uint32
end

cap_pressure = [strata_trapped.params.cap_pressure];
cap_pressure = cap_pressure.normalize();

leverett_j = cap_pressure.inv_lj(...
    strata_trapped.capillary_pressure,...
    strata_trapped.porosity,...
    strata_trapped.permeability, ...
    strata_trapped.param_ids);

dir_label = ['x','y','z'];

for direction=1:3
    file_name = [prefix,'chc',dir_label(direction),inc_ext];
    file_id = fopen(file_name,'wb','native','UTF-8');
    write_tables_for_direction(strata_trapped.idx,file_id,...
        strata_trapped.rel_perm_wat, strata_trapped.rel_perm_gas,...
        strata_trapped.saturation,leverett_j,strata_trapped.param_ids,...
        direction,offset);
    fclose(file_id);
end

end

function write_tables_for_direction(idx,file_id, krw, krg,saturations,leverett_j,param_ids,...
    direction,offset)
for cell_index = 1:length(idx)
    table_num = cell_index + length(idx) * (direction-1) + offset;

    fprintf(file_id,'CHARACTERISTIC_CURVES sfn_%u\n',table_num);
    fprintf(file_id,'%s\n%s\n',...
        'TABLE swfn_table',...
        'PRESSURE_UNITS None');

    sw = saturations(param_ids(cell_index),:);
    write_sfn_table(file_id,"SWFN",...
        sw, ...
        squeeze(krw(cell_index,direction,:)), ...
        leverett_j(cell_index,:));

    fprintf(file_id,'%s\n%s\n%s\n',...
        'END',...
        'TABLE sgfn_table',...
        'PRESSURE_UNITS None');

    sg = 1 - sw;
    sg = sg(end:-1:1);
    write_sfn_table(file_id,"SGFN",...
        sg, ...
        squeeze(krg(cell_index,direction,end:-1:1)), ...
        zeros(size(sg)));

    fprintf(file_id,'%s\n%s\n',...
        'END',...
        'END');
end
end
