compressed = compress_tables(strata_trapped.idx,strata_trapped.capillary_pressure,...
    strata_trapped.rel_perm_wat,strata_trapped.rel_perm_gas,...
    strata_trapped.porosity,strata_trapped.permeability,strata_trapped.params.cap_pressure,...
    "duplicate_tolerance",0);

error = measure_compression_error(strata_trapped,compressed)
