function write_sat_jlev(table_num, file_id, krw, krg,saturations, jlev)

    fprintf(file_id,'CHARACTERISTIC_CURVES sfn_%u\n',table_num);
    fprintf(file_id,'%s\n%s\n',...
        'TABLE swfn_table',...
        'PRESSURE_UNITS None');

    sw = saturations;
    write_sfn_table(file_id,"SWFN",...
        sw, ...
        squeeze(krw), ...
        jlev);

    fprintf(file_id,'%s\n%s\n%s\n',...
        'END',...
        'TABLE sgfn_table',...
        'PRESSURE_UNITS None');

    sg = 1 - sw;
    sg = sg(end:-1:1);
    write_sfn_table(file_id,"SGFN",...
        sg, ...
        squeeze(krg(end:-1:1)), ...
        zeros(size(sg)));

    fprintf(file_id,'%s\n%s\n',...
        'END',...
        'END');
end
