function [options] = gen_options()
options = struct(...
    'subscale',       50*meter(), ...
    'sat_num_points', 10, ...
    'sat_tol', 1e-8, ...
    'perm_min_threshold', 1e-7 * milli() * darcy() ...
    );
end
