function [options] = gen_options()
options = struct(...
    'subscale',       20*meter(), ...
    'sat_num_points', 16, ...
    'sat_min',  0.01, ...
    'sat_tol', 1e-8, ...
    'perm_min_threshold', 1e-8 * milli() * darcy() ...
    );
end
