name: CI

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
    push:
        branches: [main]
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    lints: # fast lints
        name: Lints
        uses: ./.github/workflows/lints.yml
    matlab: # heavy MATLAB checks
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
        needs: lints
        uses: ./.github/workflows/matlab.yml
    webpage-build:
        needs: lints
        uses: ./.github/workflows/webpage-build.yml
