name: MATLAB CI checks
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  run-buildtool:
    name: Run MATLAB Build Tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
          cache: true
      - uses: matlab-actions/run-build@v2
