name: MATLAB CI checks
on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  check-2024b:
    name: Check on 2024b
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024b
          cache: true
          products: >
            Statistics_and_Machine_Learning_Toolbox
      - uses: matlab-actions/run-build@v2
  check-2023a:
    name: Check on 2023a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
          cache: true
          products: >
            Statistics_and_Machine_Learning_Toolbox
      - uses: matlab-actions/run-build@v2
