name: MATLAB CI checks
on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  run:
    strategy:
      matrix:
        matlab-release: [R2023a, R2024b]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab-release }}
          cache: true
          products: >
            Statistics_and_Machine_Learning_Toolbox
      - uses: matlab-actions/run-build@v2
