on:
    workflow_dispatch:


permissions:
    contents: write

jobs:
    matlab-repo-patch:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: djmaxus/matlab-repo-init/.github/actions/patch@v0.8.2
