name: Release automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  pages: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          target-branch: main
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag annotation
        if: ${{ steps.release.outputs.release_created }}
        run: |
          tag="v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin --tags
          git checkout ${tag}
          git tag --annotate --force ${tag} -m "${tag}"
          git push origin ${tag} --force
      - name: Attach repository archive
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          asset_name="${{ github.event.repository.name }}-${tag}.zip"
          git archive --output ${asset_name} --verbose --worktree-attributes ${tag}
          gh release upload ${{ steps.release.outputs.tag_name }} ./${asset_name}
  webpage:
      needs: release-please
      if: ${{ needs.release-please.outputs.release_created }}
      uses: ./.github/workflows/webpage.yml
