on:
    workflow_call:

permissions:
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v5
    - uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    - uses: actions/upload-pages-artifact@v3
